CREATE TABLE IF NOT EXISTS users (
  id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name   VARCHAR(255) NOT NULL,
  email  VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name        VARCHAR(255) NOT NULL,
  description TEXT         NOT NULL,
  available   BOOLEAN      NOT NULL,
  owner_id    BIGINT       NOT NULL,
  request_id  BIGINT,
  CONSTRAINT pk_item PRIMARY KEY (id),
  CONSTRAINT fk_item_owner FOREIGN KEY (owner_id)
      REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_items_owner  ON items(owner_id);
CREATE INDEX IF NOT EXISTS idx_items_avail  ON items(available);
CREATE INDEX IF NOT EXISTS idx_items_name   ON items(name);

CREATE TABLE IF NOT EXISTS bookings (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_time TIMESTAMP NOT NULL,
  end_time   TIMESTAMP NOT NULL,
  item_id    BIGINT    NOT NULL,
  booker_id  BIGINT    NOT NULL,
  status     VARCHAR(16) NOT NULL,
  CONSTRAINT fk_booking_item   FOREIGN KEY (item_id)
      REFERENCES items(id) ON DELETE CASCADE,
  CONSTRAINT fk_booking_booker FOREIGN KEY (booker_id)
      REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bookings_item    ON bookings(item_id);
CREATE INDEX IF NOT EXISTS idx_bookings_booker  ON bookings(booker_id);
CREATE INDEX IF NOT EXISTS idx_bookings_period  ON bookings(start_time, end_time);
CREATE INDEX IF NOT EXISTS idx_bookings_status  ON bookings(status);

CREATE TABLE IF NOT EXISTS comments (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text      TEXT      NOT NULL,
  item_id   BIGINT    NOT NULL,
  author_id BIGINT    NOT NULL,
  created   TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_comment_item   FOREIGN KEY (item_id)
      REFERENCES items(id) ON DELETE CASCADE,
  CONSTRAINT fk_comment_author FOREIGN KEY (author_id)
      REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_comments_item   ON comments(item_id);
CREATE INDEX IF NOT EXISTS idx_comments_author ON comments(author_id);
CREATE INDEX IF NOT EXISTS idx_comments_created ON comments(created);
